apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoidGVzdG9yZzA4IiwicGFzc3dvcmQiOiJnaHBfaVo0MUgxMVFKanJEUXdOQzZYS2VidWhlM0Z3eEtVMEpMTHZ3IiwiYXV0aCI6ImRHVnpkRzl5WnpBNE9tZG9jRjlwV2pReFFERXhVVXBxY2tSUmQwNURObGhMWldKMWFHVXpSbmQ0UzFVd1NreE1kbmM9In19fQ==