apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: auth-dev

resources:
  - ../../base

patchesStrategicMerge:
  - deployment-patch.yaml

commonLabels:
  conga.io/environment: dev

images:
  - name: nginx
    newTag: 1.21-alpine